Repository pysal/esda, pull requests merged in 2019-06, with the labels that each got.

#58 [WIP] Contributing Smaup test to `esda`
  doc/_static/references.bib
  esda/smaup.py
  esda/tests/test_smaup.py
  notebooks/Spatial Autocorrelation for Areal Unit Data.ipynb
Labels: WIP, enhancement

#52 (ENH) FDR-based adjustment to account for multiple testing in local statistics
  doc/_static/references.bib
  doc/api.rst
  esda/__init__.py
  esda/tests/test_util.py
  esda/util.py
Labels: enhancement

#62 2.1.0
  .travis.yml
  doc/api.rst
  esda/__init__.py
  esda/getisord.py
  esda/smaup.py
Labels: WIP
