Repository pysal/esda, pull requests merged in 2020-07, with the labels that each got.

#124 BUG: fix join_count contingency table
  esda/join_counts.py
  tests/test_join_counts.py
Labels: bug

#128 [WIP, ENH] Moving to github actions for CI
  .github/workflows/unittests.yml
  .travis.yml
  MANIFEST.in
  ci/36-numba.yaml
  ci/36.yaml
  ci/37-numba.yaml
  ci/37.yaml
  ci/38-numba.yaml
  ci/38.yaml
  esda/__init__.py
  esda/tests/__init__.py
  esda/tests/test_adbscan.py
  esda/tests/test_gamma.py
  esda/tests/test_geary.py
  esda/tests/test_getisord.py
  esda/tests/test_join_counts.py
  esda/tests/test_mixture_smoothing.py
  esda/tests/test_moran.py
  esda/tests/test_silhouette.py
  esda/tests/test_smaup.py
  esda/tests/test_smoothing.py
  esda/tests/test_util.py
  requirements_plus.txt
  requirements_tests.txt
  setup.py
Labels: ci

#129 adding dependabot
  .dependabot.yml
Labels: ci, requirements/dependencies

#131 moving dependabot directory
  .github/dependabot.yml
Labels: ci, requirements/dependencies

#134 (BUG) missing comma in setup.py
  setup.py
Labels: bug
