Repository pysal/esda, pull requests merged in 2024-07, with the labels that each got.

#303 test against mac os intel chip, etc.
  .coveragerc
  .gitattributes
  .github/workflows/testing.yml
Labels: ci, maintenance

#306 `numpy.math.atan2` -> `numpy.atan2` in `shape._get_angles()`
  .gitignore
  esda/shape.py
Labels: bug

#318 modernize CI matrix & deps
  .github/workflows/build_docs.yml
  .github/workflows/testing.yml
  README.md
  ci/310-numba-oldest.yaml
  ci/310-oldest.yaml
  ci/311-latest.yaml
  ci/311-numba-latest.yaml
  ci/311.yaml
  ci/312-dev.yaml
  ci/312-latest.yaml
  ci/312-min.yaml
  ci/312-numba-dev.yaml
  ci/312-numba-latest.yaml
  ci/38-minimal-numba.yaml
  ci/38-minimal.yaml
  docs/installation.rst
  environment.yml
  esda/shape.py
  esda/tests/test_topo.py
  pyproject.toml
Labels: ci, tests, dependencies, maintenance

#325 update chat link -- gitter >> discord
  README.md
  docs/index.rst
Labels: docs

#327 ENH: natively support Graph in losh and sihouettes modules
  esda/losh.py
  esda/silhouettes.py
  esda/tests/test_losh.py
  esda/tests/test_silhouette.py
Labels: enhancement

#328 pin libpysal to 4.12
  ci/310-numba-oldest.yaml
  ci/310-oldest.yaml
  ci/311-latest.yaml
  ci/311-numba-latest.yaml
  ci/312-latest.yaml
  ci/312-min.yaml
  ci/312-numba-latest.yaml
  environment.yml
  pyproject.toml
Labels: dependencies

#329 min pin for `libpysal` in README - resolve #319
  README.md
Labels: docs, dependencies

#293 ENH: natively support Graph in moran module
  .github/workflows/testing.yml
  esda/moran.py
  esda/tests/test_moran.py
Labels: enhancement

#295 ENH: natively support Graph in all Join Counts statistics
  esda/join_counts.py
  esda/join_counts_local.py
  esda/join_counts_local_bv.py
  esda/join_counts_local_mv.py
  esda/tests/test_join_counts.py
  esda/tests/test_ljc.py
  esda/tests/test_ljc_bv.py
  esda/tests/test_ljc_mv.py
Labels: enhancement

#296 ENH: natively support Graph in all Geary statistics
  esda/geary.py
  esda/geary_local.py
  esda/geary_local_mv.py
  esda/tests/test_geary.py
  esda/tests/test_local_geary.py
  esda/tests/test_local_geary_mv.py
Labels: enhancement

#326 ENH: natively support Graph in getisord and gamma modules
  esda/gamma.py
  esda/getisord.py
  esda/tests/test_gamma.py
  esda/tests/test_getisord.py
Labels: enhancement

#332 drop `black` - reup linting w/0 Python 3.8 pin
  .pre-commit-config.yaml
  esda/adbscan.py
  esda/crand.py
  esda/gamma.py
  esda/geary.py
  esda/geary_local.py
  esda/geary_local_mv.py
  esda/getisord.py
  esda/join_counts.py
  esda/join_counts_local.py
  esda/join_counts_local_bv.py
  esda/join_counts_local_mv.py
  esda/lee.py
  esda/losh.py
  esda/map_comparison.py
  esda/mixture_smoothing.py
  esda/moran.py
  esda/shape.py
  esda/silhouettes.py
  esda/smaup.py
  esda/smoothing.py
  esda/tabular.py
  esda/topo.py
  pyproject.toml
Labels: maintenance

#339 small factor of `moran.Moran_Local_BV.__calc()`
  esda/moran.py
Labels: rough edge

#337 remove `xtyt` & `xhyh` in `shape._second_moa_ring_xplusy()`
  esda/shape.py
Labels: bug

#336 xfail for `test_G_star_Row_Standardized`
  esda/tests/test_getisord.py
Labels: ci

#341 formats, lints, pytest pt. 1 -- `test_{utils,topo}.py`
  esda/tests/test_topo.py
  esda/tests/test_util.py
Labels: maintenance

#343 formats, lints, pytest pt. 2 -- `test_adbscan.py `
  esda/tests/test_adbscan.py
Labels: maintenance
